name: Clean Artifacts

on:
    schedule:
        - cron: "0 * * * *"

jobs:
    clean:
        runs-on: self-hosted
        steps:
            - name: Cleanup
              uses: c-hive/gha-remove-artifacts@v1
              with:
                  age: "1 minute"
                  skip-recent: 20
