name: "Swiftly Compiler"

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        env:
            MMSOURCE112: ${{ github.workspace }}/swiftly/metamod
            HL2SDKCS2: ${{ github.workspace }}/swiftly/hl2sdk
        container: ${{ matrix.container }}
        strategy:
            fail-fast: false
            matrix:
                os: [self-hosted, windows-latest]
                include:
                    - os: self-hosted
                      container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  path: swiftly
                  submodules: recursive

            - name: Checkout AMBuild
              uses: actions/checkout@v4
              with:
                  repository: alliedmodders/ambuild
                  path: ambuild

            - name: Install AMBuild
              run: |
                  cd ambuild; python setup.py install; cd ..

            - name: Downloading Swiftly Utilities - Linux
              if: matrix.os == 'self-hosted'
              uses: robinraju/release-downloader@v1.8
              with:
                  repository: "swiftly-solution/swiftly-plugins-utility"
                  latest: true
                  fileName: "swiftly_utility"
                  out-file-path: "swiftly/plugin_files/scripting"

            - name: Prepare Build - Linux
              if: matrix.os == 'self-hosted'
              working-directory: swiftly
              shell: bash
              run: |
                  sudo apt install -y libreadline-dev
                  bash ./setup.sh

            - name: Prepare Build - Windows
              if: matrix.os == 'windows-latest'
              working-directory: swiftly
              run: |
                  Invoke-WebRequest -Uri https://github.com/swiftly-solution/swiftly-plugins-utility/releases/latest/download/swiftly_utility.exe -OutFile plugin_files/scripting/swiftly_utility.exe
                  ./setup.ps1

            - name: Build
              working-directory: swiftly
              run: |
                  gcc -v
                  cd build
                  ambuild

            - name: Upload Artifacts Linux
              if: matrix.os == 'self-hosted'
              uses: actions/upload-artifact@v3
              with:
                  name: Swiftly Plugin Linux
                  path: ${{ github.workspace }}/swiftly/build/package

            - name: Upload Artifacts Windows
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v3
              with:
                  name: Swiftly Plugin Windows
                  path: ${{ github.workspace }}/swiftly/build/package
